sonar.projectKey=file-service
sonar.host.url=http://localhost:9000
sonar.sources=application,library
sonar.tests=test
sonar.host.url=http://localhost:9000
sonar.token=sqp_2591ce23fa8ce8302a12da0fc2d51180b28ec0ef

sonar.exclusions=node_modules/**,static-site/**,database/**,scripts/**,docs/**,key/**,tmp/**
sonar.test.inclusions=test/**/*.test.js
sonar.javascript.lcov.reportPaths=build/reports/lcov.info
